// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: semantifly.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Semantifly_Add_FullMethodName           = "/semantifly.Semantifly/Add"
	Semantifly_Delete_FullMethodName        = "/semantifly.Semantifly/Delete"
	Semantifly_Get_FullMethodName           = "/semantifly.Semantifly/Get"
	Semantifly_Update_FullMethodName        = "/semantifly.Semantifly/Update"
	Semantifly_LexicalSearch_FullMethodName = "/semantifly.Semantifly/LexicalSearch"
)

// SemantiflyClient is the client API for Semantifly service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SemantiflyClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	LexicalSearch(ctx context.Context, in *LexicalSearchRequest, opts ...grpc.CallOption) (*LexicalSearchResponse, error)
}

type semantiflyClient struct {
	cc grpc.ClientConnInterface
}

func NewSemantiflyClient(cc grpc.ClientConnInterface) SemantiflyClient {
	return &semantiflyClient{cc}
}

func (c *semantiflyClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, Semantifly_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semantiflyClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, Semantifly_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semantiflyClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Semantifly_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semantiflyClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, Semantifly_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semantiflyClient) LexicalSearch(ctx context.Context, in *LexicalSearchRequest, opts ...grpc.CallOption) (*LexicalSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LexicalSearchResponse)
	err := c.cc.Invoke(ctx, Semantifly_LexicalSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemantiflyServer is the server API for Semantifly service.
// All implementations must embed UnimplementedSemantiflyServer
// for forward compatibility.
type SemantiflyServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	LexicalSearch(context.Context, *LexicalSearchRequest) (*LexicalSearchResponse, error)
	mustEmbedUnimplementedSemantiflyServer()
}

// UnimplementedSemantiflyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemantiflyServer struct{}

func (UnimplementedSemantiflyServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedSemantiflyServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSemantiflyServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSemantiflyServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSemantiflyServer) LexicalSearch(context.Context, *LexicalSearchRequest) (*LexicalSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LexicalSearch not implemented")
}
func (UnimplementedSemantiflyServer) mustEmbedUnimplementedSemantiflyServer() {}
func (UnimplementedSemantiflyServer) testEmbeddedByValue()                    {}

// UnsafeSemantiflyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemantiflyServer will
// result in compilation errors.
type UnsafeSemantiflyServer interface {
	mustEmbedUnimplementedSemantiflyServer()
}

func RegisterSemantiflyServer(s grpc.ServiceRegistrar, srv SemantiflyServer) {
	// If the following call pancis, it indicates UnimplementedSemantiflyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Semantifly_ServiceDesc, srv)
}

func _Semantifly_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemantiflyServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantifly_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemantiflyServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Semantifly_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemantiflyServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantifly_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemantiflyServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Semantifly_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemantiflyServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantifly_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemantiflyServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Semantifly_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemantiflyServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantifly_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemantiflyServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Semantifly_LexicalSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LexicalSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemantiflyServer).LexicalSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantifly_LexicalSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemantiflyServer).LexicalSearch(ctx, req.(*LexicalSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Semantifly_ServiceDesc is the grpc.ServiceDesc for Semantifly service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Semantifly_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "semantifly.Semantifly",
	HandlerType: (*SemantiflyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Semantifly_Add_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Semantifly_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Semantifly_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Semantifly_Update_Handler,
		},
		{
			MethodName: "LexicalSearch",
			Handler:    _Semantifly_LexicalSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "semantifly.proto",
}
