image: gitpod/workspace-postgres

ports:
  - port: 5432
    onOpen: open-preview

tasks:
  - name: Start PostgreSQL
    init: |
      pg_ctl -D /var/lib/postgresql/data start
    command: |
      psql -c "CREATE DATABASE mydatabase;"
